config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
    }
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  root to: 'tweets#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader
  

  def self.search(search)
    if search
      Tweet.where('title LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @items_array = []
    @tweets = Tweet.includes(:user)
    @tweets = Tweet.page(params[:page]).per(9).order("created_at DESC")
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
      @items.each do |item|
        @items_array.push(item)
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end
  
  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:title, :image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_header.html.haml
%nav.navbar.sticky-top.navbar-dark.bg-warning
  %a.navbar-brand 缶交大使
  %form.form-inline
  - if current_user
    = form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline") do |f|
      = f.text_field :keyword, placeholder: "投稿を検索する", class: "form-control mr-sm-2"
      = f.submit "検索", class: "btn btn-dark my-2 my-sm-0"
      =link_to "新規投稿", "/tweets/new", {method: "get",class: "btn btn-primary"}
  - else
    = form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline") do |f|
      = f.text_field :keyword, placeholder: "投稿を検索する", class: "form-control mr-sm-2"
      = f.submit "検索", class: "btn btn-dark my-2 my-sm-0"

app/views/tweets/create.html.haml
.picture-size
  %h3.mb-4
  = image_tag asset_path('投稿完了.jpg'), class: "img-thumbnail mx-auto d-block"  

  .ml-auto.posts_button
  %a.btn.btn-outline-info.btn-lg.btn-block{href: "/"} 投稿一覧へ戻る

app/views/tweets/crete.html.haml
.contents.row
  .success
    %h3 投稿が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.picture-size
  %h3.mb-4
  = image_tag asset_path('削除完了.jpg'), class: "img-thumbnail mx-auto d-block"

  .ml-auto.posts_button
  %a.btn.btn-outline-info.btn-lg.btn-block{href: "/"} 投稿一覧へ戻る

app/views/tweets/edit.html.haml
.tweet-create
  .d-flex.align-items-center
    %h1 投稿編集
    .ml-auto.posts_button
      %a.btn.btn-outline-info{href: "/"} 投稿一覧 
  = form_with(model: @tweet, local: true) do |f|
    .form-group
      %label 投稿タイトル
      = f.text_field :title, class: "form-control", placeholder: "タイトル"
      %small#emailHelp.form-text.text-muted タイトルを入力してください。
    .form-group
      %label 投稿内容
      = f.text_area :text, class: "Textarea1 form-control",rows: "10", placeholder: "投稿内容"
      %small#emailHelp.form-text.text-muted 投稿内容を入力してください。
    .form-group
      %label 写真投稿
      = f.file_field :image, class: "form-control-file", type: "file"
      %small.form-text.text-muted 写真を選択してください。
    = f.submit nil, class: "btn btn-primary"

app/views/tweets/index.html.haml
= render "header"
.main
  .container
    #main_visual.carousel.slide{"data-ride": "carousel"}
      %ol.carousel-indicators
        %li.active{"data-slide-to": "0", "data-target": "#main_visual"}
        %li{"data-slide-to": "1", "data-target": "#main_visual"}
      .carousel-inner
        .carousel-item.active
          = image_tag asset_path('缶詰一覧2.jpg'), class: "img-fluid"
          .carousel-caption.d-md-block
            %h1 好きな缶詰投稿してみませんか
            %p 缶詰は、味・保存性・栄養素が全て揃った人類の最高傑作です。是非自分の好きな缶詰を共有しましょう
        .carousel-item
          = image_tag asset_path('みかん缶のコピー.jpg'), class: "img-fluid"
          .carousel-caption.d-md-block
            %h1.text-dark 缶詰の可能性は無限大
            %p.text-dark そのまま食べるもよし。一手間加えて食べるもよし。缶詰の魅力をUPさせる食べ方を紹介して、缶詰好きの輪を広げましょう
      %a.carousel-control-prev{"data-slide": "prev", href: "#main_visual", role: "button"}
        %span.carousel-control-prev-icon{"aria-hidden": "true"}
        %span.sr-only 前に戻る
      %a.carousel-control-next{"data-slide": "next", href: "#main_visual", role: "button"}
        %span.carousel-control-next-icon{"aria-hidden": "true"}
        %span.sr-only 次に進む

.album.py-5.bg-light
  .container
    .row
      - @tweets.each do |tweet|
        .col-md-4
          .card.mb-4
            .image-box
              = image_tag tweet.image.url, class: 'bd-placeholder-img card-img-top thumnail' if tweet.image.present?
            .card-body
              %p.card-text
                = tweet.title
              .d-flex.justify-content-between.align-items-center
                .btn-group.btn
                  =link_to "詳細", tweet_path(tweet.id), {method: "get", class: "btn btn-sm btn-outline-secondary"}
                  - if user_signed_in? && current_user.id == tweet.user_id
                    =link_to "編集", edit_tweet_path(tweet.id), {method: "get",class: "btn btn-sm btn-outline-secondary"}
                    =link_to "削除", tweet_path(tweet.id), {method: "delete",class: "btn btn-sm btn-outline-secondary"}

  =paginate(@tweets)

  %h1.text-center.text-white.bg-danger ↓↓気になる缶詰があれば楽天で検索↓↓
  .content.text-right
    #search-box.w-100
      = form_with url: tweets_path, method: 'get', local: true do |f|
        = f.text_field :keyword, placeholder: "検索したい商品を入力してください", class: "form-control mr-sm-2."
        = f.submit "検索", class: "btn btn-primary"
    %h2.text-center 検索結果

  %table.table.table-striped
    %thead
      %tr
        %th{scope: "col"} 商品名
        %th{scope: "col"} 価格
        %th{scope: "col"} 商品画像
      %tbody
      - if @items.present?
        - @items.each do |item|
          %tr
            %td= link_to item.name, "#{item.url}"
            %td{align: "right"}
              = item['itemPrice']
              円
            %td=image_tag item["smallImageUrls"][0]

app/views/tweets/new.html.haml
.tweet-create
  .d-flex.align-items-center
    %h1 新規投稿
    .ml-auto.posts_button
      %a.btn.btn-outline-info{href: "/"} 投稿一覧 
  = form_with(model: @tweet, local: true) do |f|
    .form-group
      %label 投稿タイトル
      = f.text_field :title, class: "form-control", placeholder: "タイトル", required: true, minlength: @title_length, maxlength: '30'
      %small#emailHelp.form-text.text-muted タイトルを入力してください。
    .form-group
      %label 投稿内容
      = f.text_area :text, class: "Textarea1 form-control",rows: "10", placeholder: "投稿内容", required: true, minlength: @text_length, maxlength: '500'
      %small#emailHelp.form-text.text-muted 投稿内容を入力してください。
    .form-group
      %label 写真投稿
      = f.file_field :image, class: "form-control-file bs-custom-file-input", type: "file"
      %small.form-text.text-muted 写真を選択してください。(ファイルをドロップする事も出来ます。)
    = f.submit nil, class: "btn btn-primary"
    

app/views/tweets/search.html.haml
= render "header"

.album.py-5.bg-light
  .container
    .row
      - @tweets.each do |tweet|
        .col-md-4
          .card.mb-4.shadow-
            .image-box
              = image_tag tweet.image.url, class: 'bd-placeholder-img card-img-top thumnail' if tweet.image.present?
            .card-body
              %p.card-text
                = tweet.title
              .d-flex.justify-content-between.align-items-center
                .btn-group.btn
                  =link_to "詳細", tweet_path(tweet.id), {method: "get", class: "btn btn-sm btn-outline-secondary"}
                  - if user_signed_in? && current_user.id == tweet.user_id
                    =link_to "編集", edit_tweet_path(tweet.id), {method: "get",class: "btn btn-sm btn-outline-secondary"}
                    =link_to "削除", tweet_path(tweet.id), {method: "delete",class: "btn btn-sm btn-outline-secondary"}

app/views/tweets/show.html.haml
.tweet-create
  .show
    .d-flex.justfy-content-space-between
      %h1.bg-info.rounded.text-white 投稿詳細
      .ml-auto.posts_button
        %a.btn.btn-outline-info{href: "/"} 投稿一覧 
    .card.mb-4
      = image_tag "#{@tweet.image}", class: 'bd-placeholder-img card-img-top'
      %h5.bg-info.rounded.text-white 投稿内容
      %p.card-text
        = @tweet.text
    .form-group
      - if current_user
        = form_with(model: [@tweet, @comment], local: true, id: "new_comment") do |f|
          %label.bg-info.rounded.text-white ＜コメント投稿＞
          = f.text_area :text, class: "Textarea1 form-control textbox", rows: "3", placeholder: "コメントする"
          %small#emailHelp.form-text.text-muted コメントを入力してください。
          = f.submit nil, class: "btn btn-primary form__submit"
      - else
        %strong
          %p.bg-info.rounded.text-white.text-center ~~~ コメントを投稿するには新規登録／ログインが必要です ~~~
      .comments
        %label ＜コメント一覧＞
        - if @comments
          - @comments.each do |comment|
            %p
              %strong
                = link_to comment.user.nickname, "/users/#{comment.user_id}"
              = comment.text

app/views/tweets/update.html.haml
.picture-size
  %h3.mb-4
  =image_tag asset_path('編集完了.jpg'), class: "img-thumbnail mx-auto d-block"

  .ml-auto.posts_button
  %a.btn.btn-outline-info.btn-lg.btn-block{href: "/"} 投稿一覧へ戻る